[project]
name = "flick"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "flask>=3.1.1",
    "flask-cors>=6.0.1",
    "importlib>=1.0.4",
    "loguru>=0.7.3",
    "pywebview>=5.4",
    "requests>=2.32.4",
]
